---

- name: Install docker and kubernetes master node
  hosts: master-node
  become: true
  remote_user: root

  roles:
   - docker-role
   - master-role

- name: Install docker and kubernetes on worker node
  hosts: worker-node
  become: true
  remote_user: root

  roles:
   - docker-role
   - worker-role


